### ISSUE TITLE
Question regarding pulling bds like functionality

### ISSUE THREAD

**Issue by ahmasoh1992** [matthewgilbert/pdblp#26] opened 2018-02-15 09:05 UTC
Hey, 

If I have a request to pull the historical composition of a dataset, say:

```python
X = con.ref('TPX500 Index','INDX_MWEIGHT_HIST', [('END_DT','19991231'),])

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\...\Python27\site-packages\pdblp\pdblp.py", line 242, in ref
    ovrds, [])
  File "C:\...\Python27\site-packages\pdblp\pdblp.py", line 116, in _create_req
    request = self.refDataService.createRequest(rtype)
AttributeError: 'BCon' object has no attribute 'refDataService'
```

Any help?? Not sure what's going on!

**Comment by matthewgilbert** [comment] 2018-02-15 12:25
I would guess the problem is you are not running `con.start()` before making your call to `ref()`. Please take some time to read the documentation, as both this and #25 are discussed in the [tutorial](https://matthewgilbert.github.io/pdblp/tutorial.html) as well as the docstrings of the relevant methods.

I do agree that the error message could be more informative if you have not started a connection already.

**Comment by ahmasoh1992** [comment] 2018-02-15 12:37
Hi Matthew, 

I only sent a code snippet above, the full code looks like this:

```
import pandas as pd
import numpy as np

con = pdblp.BCon(debug=False, port=8194)
con.start()
con = pdblp.BCon(timeout=5000)

dts = [d.strftime('%Y%m%d') for d in pd.date_range('19991231','20180212')]

universes = ['SPX']

str_index = univ + ' Index'

X = con.ref(str_index,'INDX_MWEIGHT_HIST', [('END_DT','19991231'),])
```

I have read the documentation...but it doesn't seem to want to pull data where the number of stocks per index is greater than a few hundred, for some reason!

**Comment by matthewgilbert** [comment] 2018-02-15 12:45
Could you set `con = pdblp.BCon(debug=True, port=8194)` and include the output from this? Not sure what is going on here since this syntax does not look problematic. Possibly related to hitting BBG terminal data limits since you mention you are pulling data on hundreds of instruments.

**Comment by ahmasoh1992** [comment] 2018-02-15 12:52
Hey Matt, 

Thanks for the help. Bit confused myself here. 

I don't seem to get any different output when setting the debug=True:

```
Traceback (most recent call last):
  File "<input>", line 10, in <module>
  File "C:\Users\sahmad\AppData\Roaming\Python\Python27\site-packages\pdblp\pdblp.py", line 242, in ref
    ovrds, [])
  File "C:\Users\sahmad\AppData\Roaming\Python\Python27\site-packages\pdblp\pdblp.py", line 116, in _create_req
    request = self.refDataService.createRequest(rtype)
AttributeError: 'BCon' object has no attribute 'refDataService'

````

**Comment by matthewgilbert** [comment] 2018-02-15 12:57
It's very difficult for me to tell conclusively unless you post short reproducible snippets. For example in your above post you have
```python
import pandas as pd
import numpy as np

con = pdblp.BCon(debug=False, port=8194)
con.start()
con = pdblp.BCon(timeout=5000)

str_index = 'SPX Index'

X = con.ref(str_index,'INDX_MWEIGHT_HIST', [('END_DT','19991231'),])
```

which first creates a  connection and assigns it to `con`, `con = pdblp.BCon(debug=False, port=8194)`, then appropriately starts the connection `con.start()`, then reassigns a new connection to `con`, `con = pdblp.BCon(timeout=5000)` which you never end up starting. This is what leads me to believe you are not appropriately starting the connection.

**Comment by ahmasoh1992** [comment] 2018-02-15 13:15
Weirdly if I add a con.restart()

For example:

```
import pandas as pd
import numpy as np

con = pdblp.BCon(debug=False, port=8194)
con.start()
con = pdblp.BCon(timeout=5000)
con.restart()

str_index = 'SPX Index'

X = con.ref(str_index,'INDX_MWEIGHT_HIST', [('END_DT','19991231'),])
```

Then it works...?

**Comment by matthewgilbert** [comment] 2018-02-15 13:20
This is not weird at all, this is expected behavior
```python
con = pdblp.BCon(debug=False, port=8194)
con.start()
con = pdblp.BCon(timeout=5000)
con.start()
```
would also work since you need to start the second connection. In the example
```python
con = pdblp.BCon(debug=False, port=8194)
con.start()
con = pdblp.BCon(timeout=5000)
```
those two `con` variables are different instances, since you have reassigned the value.

This would parallel writing

```
a = 3
a = 7
```
clearly `a` is not `3` after running this. Equivalently, you have a new connection instance, that generated by running `con = pdblp.BCon(timeout=5000)`, that you never start in your previous examples.

**Comment by ahmasoh1992** [comment] 2018-02-15 13:28
Ah thanks Matt! Cheers for the help and awesome library - working like a dream now.

**Closed** 2018-02-16 13:27 UTC
Labels: question
